name: "Update DependencyControl feed"

on:
  push:
    branches:
      - main

jobs:
  depctrl-feed:
    name: "Update DependencyControl Feed"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.repository.default_branch }}

      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: pip install pyyaml

      - name: "Update DependencyControl Feed"
        run: python .github/workflows/generate_feed.py

      - name: "Commit Changes"
        run: |
          git config user.name "DepCtrl Updater"
          git config user.email github-actions@github.com
          git add DependencyControl.json
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update depctrl feed"; git push)
